#!/usr/bin/env python3
"""
Does the loop on the phone have both of its ends?

The app's cord (FlyBrain/Sources/FlyCord.swift) is four lines of arithmetic
around three questions asked by name:

    how fast is `pool:T1_left:tibia_flexor` firing?      (a muscle pool)
    (drive) `organ:T1_left:chordotonal` at this current  (a sense organ)
    which joint does the asset say that pool moves?      (the body asset)

Every one of those names has to exist in *two* files that are generated by
different tools: `build/fly_body.json` (tools/build_body.py, from the MJCF) and
`build/flybanc.bin` + `build/flybanc_meta.json` (tools/build_banc.py, from BANC).
If a name means one thing in one file and something else in the other, the cord
reads 0 Hz — and 0 Hz is indistinguishable from a pool that is simply quiet.
That failure looks exactly like a plausible animal doing nothing, which is the
one thing this repository is built to avoid.

So this checks, on the files the app will actually ship:

  1. every pool group the body asset names is in the connectome's group list,
  2. and is not empty (a pool with no motor neurons is silence, not a muscle),
  3. every organ group the body asset names is in the connectome's group list,
  4. and is not empty,
  5. every pool lands on a hinge the body asset actually has,
  6. the loop's shape: 6 legs, 3 joints each, 2 organs each,
  7. the asset reports what it could not place rather than dropping it.

Run from the repository root, after both packers:

    python3 tools/build_body.py --flybody data/flybody \\
        --out build/fly_body.json --meshes build/fly_meshes.bin
    python3 tools/build_banc.py --raw data/banc --out build/flybanc.bin
    python3 tools/verify_loop.py
"""

from __future__ import annotations
import argparse
import json
import pathlib
import struct
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
MAGIC = b"FLYBANC_"


def read_groups(meta_path: pathlib.Path):
    """(name, count) for every group in the built connectome."""
    meta = json.loads(meta_path.read_text())
    return [(g["name"], int(g["count"])) for g in meta.get("groups", [])]


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--body", default=ROOT / "build" / "fly_body.json",
                    type=pathlib.Path)
    ap.add_argument("--meta", default=ROOT / "build" / "flybanc_meta.json",
                    type=pathlib.Path)
    ap.add_argument("--bin", default=ROOT / "build" / "flybanc.bin",
                    type=pathlib.Path)
    args = ap.parse_args()

    for p in (args.body, args.meta):
        if not p.exists():
            print(f"  missing {p}")
            return 2

    body = json.loads(args.body.read_text())
    groups = read_groups(args.meta)
    by_name = dict(groups)

    hinges = {j["name"] for j in body["joints"] if j["kind"] == "hinge"}
    legs = body["legs"]

    problems: list[str] = []
    pool_groups: list[str] = []
    organ_groups: list[str] = []
    placed = 0
    unplaced = 0

    for key, leg in sorted(legs.items()):
        for name, pool in leg["pools"].items():
            pool_groups.append(pool["group"])
            placed += 1
            # The asset names a pool's joint by the short key the mapper uses
            # ("tibia"), and the hinge by its full name ("tibia_T1_left"), which
            # is what FlyCord resolves through this same table.
            short = pool["joint"]
            full = leg["joints"].get(short, {}).get("name")
            if full is None:
                problems.append(
                    f"{key}: pool '{name}' is placed on '{short}', which is not "
                    f"one of the leg's three joints")
            elif full not in hinges:
                problems.append(
                    f"{key}: pool '{name}' names joint '{short}' -> '{full}', "
                    f"which is not a hinge in the asset")
            if pool["qpos_sign"] not in (-1, 1):
                problems.append(
                    f"{key}: pool '{name}' has qpos_sign "
                    f"{pool['qpos_sign']}, which is not a direction")
        unplaced += len(leg.get("pools_not_placed", []))
        organs = leg.get("organs", {})
        if set(organs) != {"chordotonal", "campaniform"}:
            problems.append(
                f"{key}: the leg reports organs {sorted(organs)}, not the two "
                f"the loop drives")
        for kind, organ in sorted(organs.items()):
            if not organ.get("group"):
                problems.append(f"{key}: organ '{kind}' has no group name")
                continue
            organ_groups.append(organ["group"])
            if kind == "chordotonal" and not organ.get("joint"):
                problems.append(f"{key}: the chordotonal organ names no joint")

    for what, names in (("pool", pool_groups), ("organ", organ_groups)):
        for n in names:
            if n not in by_name:
                problems.append(
                    f"the connectome has no {what} group '{n}' — the loop would "
                    f"read it as silence")
            elif by_name[n] == 0:
                problems.append(f"the connectome's {what} group '{n}' is empty")

    n_pool_named = len({g for g in by_name if g.startswith("pool:")})
    n_organ_named = len({g for g in by_name if g.startswith("organ:")})

    checks = [
        ("six legs", len(legs) == 6),
        ("three joints per leg, all of them hinges",
         all(len(l["joints"]) == 3 and all(j["name"] in hinges
                                           for j in l["joints"].values())
             for l in legs.values())),
        ("every pool the asset places exists in the connectome",
         all(g in by_name for g in pool_groups)),
        ("every organ the asset names exists in the connectome",
         all(g in by_name for g in organ_groups)),
        ("no group the loop needs is empty",
         all(by_name.get(g, 0) > 0 for g in pool_groups + organ_groups)),
        ("the connectome carries one group per pool, per leg and side",
         n_pool_named >= 6 * len({p.split(":")[2] for p in pool_groups})),
        ("the connectome carries both organs for every leg",
         n_organ_named >= 12),
        ("nothing the body could not place was dropped",
         not [p for l in legs.values() for p in l.get("pools_not_placed", [])
              if p.get("reason") == "joint not modelled"]),
    ]
    ok = True
    for label, cond in checks:
        print(f"  {'ok  ' if cond else 'FAIL'} {label}")
        ok &= bool(cond)
    for p in problems:
        print(f"  FAIL {p}")
        ok = False

    print(f"  the loop: {len(legs)} legs · {placed} pools placed · "
          f"{unplaced} pools the body could not place · "
          f"{len(organ_groups)} organs")
    print(f"  the connectome names {n_pool_named} pools and {n_organ_named} "
          f"organs; the body asks for {len(set(pool_groups))} and "
          f"{len(set(organ_groups))}")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
